#try except

#num = 3
try:
    print(num)
    
except:
    print("AN Exception is occured!")
